// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRnP6Yaj7CcontJpH6pPKsRP1jA4Y4GiA',
    appId: '1:576808977815:web:0ca6cbe25cb0e2a664f0d2',
    messagingSenderId: '576808977815',
    projectId: 'smartpark-c60bb',
    authDomain: 'smartpark-c60bb.firebaseapp.com',
    storageBucket: 'smartpark-c60bb.appspot.com',
    measurementId: 'G-6TWYWMWJBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu0jZ9Avric-UnwftMkUNPScZXQYahKlk',
    appId: '1:576808977815:android:5bfae960f92152b764f0d2',
    messagingSenderId: '576808977815',
    projectId: 'smartpark-c60bb',
    storageBucket: 'smartpark-c60bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWKp6Na6ImGca1gr29mqtvfZxLfMLyOMM',
    appId: '1:576808977815:ios:7306c338df0517e064f0d2',
    messagingSenderId: '576808977815',
    projectId: 'smartpark-c60bb',
    storageBucket: 'smartpark-c60bb.appspot.com',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWKp6Na6ImGca1gr29mqtvfZxLfMLyOMM',
    appId: '1:576808977815:ios:7306c338df0517e064f0d2',
    messagingSenderId: '576808977815',
    projectId: 'smartpark-c60bb',
    storageBucket: 'smartpark-c60bb.appspot.com',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRnP6Yaj7CcontJpH6pPKsRP1jA4Y4GiA',
    appId: '1:576808977815:web:d5397bfa82d7932564f0d2',
    messagingSenderId: '576808977815',
    projectId: 'smartpark-c60bb',
    authDomain: 'smartpark-c60bb.firebaseapp.com',
    storageBucket: 'smartpark-c60bb.appspot.com',
    measurementId: 'G-BVJPE1Q94N',
  );
}